version: '3.8'
services:
  foosladder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_FOOSBALL_PASSWORD: ${NEXT_PUBLIC_FOOSBALL_PASSWORD}
    # Ensure you have a .env.local file or set these environment variables in your VPS environment
