version: '3.8'
services:
  foosladder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
# Ensure you have a .env file or set these environment variables in your VPS environment
